require 'sponsored/advertiser'
require 'sponsored/amazon_search'
require 'sponsored/babelfy_client'
require 'sponsored/bitly_client'
require 'sponsored/exhaustive_search'
require 'sponsored/google_search'
require 'sponsored/plugin'
require 'sponsored/search'
