- name: WALIKI TOYS Hopper Ball For Adults Mr Jones (Hippity Hop Ball, Hopping Ball, Bouncy Ball With Handles, Sit & Bounce, Space Hopper, Kangaroo Bouncer, Jumping Ball, Ages 13-101, 29", Plush Horse, Pump)
  url: https://www.amazon.com/dp/B00BPHH7DU/
  image: https://images-na.ssl-images-amazon.com/images/I/616t9BDPnkL._SL1000_.jpg
  price: $50.98
  features:
    - Yeeeha!!! Huge Ball, 29" diameter.
    - Race friends and family alike. Wear a Horse Mask at your own risk.
    - Free, easy to use double action PUMP, ball, and plush cover included.
    - Huge head! Larger than a human head.
- name: Save Brands East Butter Savers, Yellow
  url: https://www.amazon.com/dp/B0078QIG46/
  image: https://images-na.ssl-images-amazon.com/images/I/61Q8-F-GtxL._SL1500_.jpg
  price: $13.63
  features:
    - Reusable and durable end caps designed to help keep your butter stick protected
    - Patented design easily measures out 1 Tablespoon of butter
    - EAST COAST butter savers fit the longer and thinner style butter sticks with 1 1/4 inch width
    - Prevents waste of plastic wrap, bags and foil to save your butter stick
- name: '1000 Famous Horses Fact & Fictional Throughout the Ages: (Not Race Horses and Not Show Jumping Horses)'
  url: https://www.amazon.com/dp/B004YQG56Y/
  image: https://images-na.ssl-images-amazon.com/images/I/41%2B2UD1ufwL.jpg
  price: $23.99
  features:
    - Not Race Horses
    - Not Show Jumping Horses
- name: Cute Banana Radiation-proof Handset for iPhone
  url: https://www.amazon.com/dp/B00APVSTPM/
  image: https://images-na.ssl-images-amazon.com/images/I/31kJsjR4I7L.jpg
  price: $34.99
  features:
    - Color:yellow
    - Material:pc
    - 'Size: For iPhone,Motorola and Blackberry and most phones'
- name: "Essential Oils for Children: 40 Essential Oil Recipes for Your Kids' Health"
  url: https://www.amazon.com/dp/B01NAIU3KW/
  image: https://images-na.ssl-images-amazon.com/images/I/51BWzbPiLPL.jpg
  price: $8.99
  features:
    - Keep essential oils away from eyes and ears.
    - People that suffer from epilepsy should avoid using essential oils especially Idaho tansy.
    - A safe area to apply essential oils is on the feet.
    - Before ingesting essential oils make sure that they are "GRAS" (generally regarded as safe).
    - Do not add essential oils that have not been diluted to your bath water.
- name: GreatGadgets 1880 Genuine Leather Classic Beer Holster, Espresso Brown
  url: https://www.amazon.com/dp/B007N9OWKU/
  image: https://images-na.ssl-images-amazon.com/images/I/91%2B9CWNZz2L._SL1500_.jpg
  price: $19.90
  features:
    - Convenient holster for all standard size 12 oz. beer/soda bottles and cans
    - Fits all belts (not included in the delivery) of up to about 1.5 Inch in width
    - 'Perfect for barbecues, parties, picnics, DIY jobs and gardening around the house: both hands are free and your cold beverage is always within reach'
    - "Men's best friend: unique gift for all men (because a real cowboy needs his holster!)"
- name: 16x24 16"x24" 40x60cm Body pillow covers cases Polyester & Cotton Print cool Jeff Goldblum
  url: https://www.amazon.com/gp/product/B017K15SQ2/
  image: https://images-na.ssl-images-amazon.com/images/I/41UASn-vHhL.jpg
  price: $9.80
  features:
    - Brand new 1PC cushion cover(INSERT NOT INCLUDED)
    - This case(cover) has a zipper
    - Made of durable cotton belend linen material
    - The pattern is only on the front side
- name: '#gomphosis - Hashtag Adult Baseball Hat'
  url: https://www.amazon.com/dp/B01NH1A28T/
  image: https://images-na.ssl-images-amazon.com/images/I/51kjafyNoqL._UX679_.jpg
  price: $22.99
  features:
    - Flexfit Wooly Hat
    - Combed Twill (63% Polyester, 36% Cotton, 3% Spandex)
    - Athletic Shape, with Flexfit band
- name: ForeverSpin Tactical Titanium Spinning Top, Titanium
  url: https://www.amazon.com/dp/B00O397DI6/
  image: https://images-na.ssl-images-amazon.com/images/I/31BTmkVKZ6L.jpg
  price: $47.00
  features:
    - Solid Titanium Metal Spinning Top
    - Made In Canada
    - Precision hi-tech CNC-machined
    - Holographic Serial Number
- name: Funny Sleeveless T-Shirt (You think Im a loser / meet my dog) Shooter Tee Shirt
  url: https://www.amazon.com/dp/B014Q0MIJU/
  image: https://images-na.ssl-images-amazon.com/images/I/61jmUMRAqRL._UL1500_.jpg
  price: $16.95
  features:
    - 100% Cotton
    - Made in USA and Imported
    - Exactly as Pictured; Embellished & Shipped from CA, USA
    - Signature Depot Brand Item, Great Gift Idea; Seamless Collar, Hemmed Armholes, & Double-Needle Bottom Hem Shooter Basketball T-Shirt
- name: 'Music Cats Love: While You Are Gone'
  url: https://www.amazon.com/dp/B001AJZ3R0/
  image: https://images-na.ssl-images-amazon.com/images/I/51fvoSdx1HL._SS500_PJStripe-Robin-Large,TopLeft,0,0.jpg
  price: $13.99
  features:
    - Paws and Claws
    - Chasing Shadows
    - Purrfect Mood
    - Window Watching
    - Musical Catnip
    - Twisted Whisker
    - Furry Flurry
    - A Sunny Spot
- name: GoPet Treadwheel ToySmall (<25lbs)
  url: https://www.amazon.com/dp/B006GR9EAS/
  image: https://images-na.ssl-images-amazon.com/images/I/61LSLyDdNtL._SL1000_.jpg
  price: $375.98
  features:
    - Dog Powered - Does not Require Electricity
    - Dogs Can Use the TreadWheel Even When Home Alone
    - Gives your Canine the Freedom of an Off-Leash Run, at Their Own Natural Pace
- name: Mystic Emoji Ball
  url: https://www.amazon.com/dp/B01FOOJC64/
  image: https://images-na.ssl-images-amazon.com/images/I/51QDkLt3NgL._SL1000_.jpg
  price: $9.95
  features:
    - Just Shake, Turn Over and Reveal Your Fortune; Fortune Teller Answers In Words, Txt Slang & Emojis
    - 12 Different Possible Answers; All Answers Include Emoji Icon
- name: Dr. Bailey's Secure Instant Smile Upper -One Size Fits Most
  url: https://www.amazon.com/dp/B0024825Y0/
  image: https://images-na.ssl-images-amazon.com/images/I/51VPt90MiqL._SL1107_.jpg
  price: $10.97
  features:
    - One Size Fits Most
    - For Temporary Use Only
    - Easy To Follow Instructions And Take Only A Few Minutes Using Hot Water And Can Be Done In The Privacy Of Your Home
    - For Temporary Aesthetic Purposes Only, Do Not Eat Or Sleep While Using This Product
- name: Chatty Patty - Electronic Talking Repeating Parrot Parakeet Bird
  url: https://www.amazon.com/dp/B00NB2P86K/
  image: https://images-na.ssl-images-amazon.com/images/I/41pB5Veg3eL.jpg
  price: $18.99
  features:
    - Immediately repeats everything people say
    - Whistles and laughs by itself
    - Moves its beak, rocks back and forth, flaps its wings
    - Starts recording people’s voices as soon as they start talking
- name: Fun Bell Toy Ring for Me Call Bell Party Prop Toy - Gift for Lovers, Valentine and Wedding
  url: https://www.amazon.com/dp/B00PRVCSNY/
  image: https://images-na.ssl-images-amazon.com/images/I/61KpSGFp0ML._SL1001_.jpg
  price: $7.59
  features:
    - This creative bell with the words "Ring for Sex/ Ring for Me" on it is a fun item for adults.
    - Wedding Gift Ideas
    - Go to bid it ,it will bring you a surprise
    - Ring bell can make you couple a wonderful time
- name: The Clapper Sound Activated On/Off Switch
  url: https://www.amazon.com/dp/B0000CGKLR/
  image: https://images-na.ssl-images-amazon.com/images/I/51KAALSji6L.jpg
  price: $34.99
  features:
    - Turn on household devices with the clap of your hands
    - Plugs into standard light sockets
    - Contains one Clapper
- name: GlowBowl A-00452-01 Motion Activated Toilet Nightlight
  url: https://www.amazon.com/GlowBowl-00452-01-Motion-Activated-Nightlight/dp/B018Z0TE3K/
  image: https://images-na.ssl-images-amazon.com/images/I/81AW-S-OSiL._SL1500_.jpg
  price: $10.40
  features:
    - Fits ANY Toilet!! Flexible are that will take the shape of any type toilet and will stay in place.
    - Select from 7 LED colors with just the press of a button. (blue, yellow, purple, white, aqua, red, and green)
    - Carousel mode that will rotate colors automatically every 4 seconds if selected.
- name: Rx Destroyer Pharmaceutical Disposal System
  url: https://www.amazon.com/dp/B01LYBLHMP/
  image: https://images-na.ssl-images-amazon.com/images/I/31%2BctA4s5lL.jpg
  price: $13.84
  features:
    - Eco-friendly drug disposal system
    - Solution starts to dissolve medications and pills on contact
    - Safe and effective for use on tablets, capsules, creams and more
- name: GOT ATKINS? Family Name Steel Metal License Plate Frame
  url: https://www.amazon.com/dp/B00E7BLDX6/
  image: https://images-na.ssl-images-amazon.com/images/I/518EL0gFS4L._SL1024_.jpg
  price: $12.99
  features:
    - High Quality Stainless Steel Metal License Plate Frame.
    - Heavy Duty Product.
    - Great Gift Idea For Family And Friends.
- name: Little Buddy Cup Trophy with 3 lines of custom text
  url: https://www.amazon.com/dp/B00CAAQDBS/
  image: https://images-na.ssl-images-amazon.com/images/I/418nuqr6NIL.jpg
  price: $9.99
  features:
    - 4" Little Buddy Cup Trophy
    - A fun and unqiue recognition award that is value priced and sure to please. Perfect to recognize any achievement
    - Made of resin
- name: Rapid Pizza ReHeater - Reheat Perfect Pizza Every Time!
  url: https://www.amazon.com/dp/B01AGZD5BE/
  image: https://images-na.ssl-images-amazon.com/images/I/81Iexl1vG4L._SL1500_.jpg
  price: $6.10
  features:
    - Reheat DELICIOUS pizza in the microwave every time!
    - NO MORE soggy pizza – get the FRESH out of the box taste!
    - The PERFECT addition to your kitchen! MUST HAVE for students, busy parents, and leftover lovers!
    - HEAT and EAT off of the cooker!
- name: Electronic Bumper Sticker 8" x 2" by Talelight
  url: https://www.amazon.com/dp/B01N7TM5V0/
  image: https://images-na.ssl-images-amazon.com/images/I/81CEnl7tQzL._SL1500_.jpg
  price: $129.85
  features:
    - Introducing the World's First Electronic Bumper Sticker!
    - 'Talelight: The Slicker Bumper Sticker.'
- name: Giant Gummy Pizza in a Box (16oz)
  url: https://www.amazon.com/dp/B01DYSEU5U/
  image: https://images-na.ssl-images-amazon.com/images/I/41fYGEZ6QnL.jpg
  price: $24.95
  features:
    - Giant gummy pizza in pizza box
- name: Tablift Tablet Stand for the Bed, Sofa, or Any Uneven Surface
  url: https://www.amazon.com/dp/B01AHGIDE6/
  image: https://images-na.ssl-images-amazon.com/images/I/81Xp-aV1FIL._SL1500_.jpg
  price: $39.95
  features:
    - Flexible and stable design perfect the bed, the couch, or any uneven surface
    - Flexible legs will fold down to compact size
    - The Tablift transforms your tablet experience in the places you use your tablet the most
- name: Star Wars Rogue One Darth Vader Light Saber Handheld Immersion Blender
  url: https://www.amazon.com/dp/B01HZQEM5A/
  image: https://images-na.ssl-images-amazon.com/images/I/61x9z4AZ9lL._SL1024_.jpg
  price: $29.99
  features:
    - Mix your soups and smoothies with this light saber-inspired immersion blender
    - Finely detailed ABS handle with a metal look and feel to replicate Darth Vader's iconic weapon
    - Makes a perfect gift for the culinary-minded Star Wars fan
- name: Big Mens Sanford Lightweight Cotton Jacket by TR Gold
  url: https://www.amazon.com/dp/B001GW9570/
  image: https://images-na.ssl-images-amazon.com/images/I/61qFqy3NlyL._SL1024_.jpg
  price: $110.99
  features:
    - Adjustable snap cuffs and an open draw cord lower edge will give you a custom fit in this lightweight jacket
    - 8.2 oz. 100% peached cotton shell stone colored cotton poplin lining
    - Exterior side pockets zippered security pocket side panel key pocket inner cell phone pocket with Velcro closure
- name: Four Sigmatic Organic Mushroom Coffee with Lion’s Mane & Chaga
  url: https://www.amazon.com/dp/B00ZWA7LQ4/
  image: https://images-na.ssl-images-amazon.com/images/I/81J5s89RElL._SL1500_.jpg
  price: $12.34
  features:
    - Vegan, vegetarian, & paleo friendly
    - 500 mg of dual-extracted lion’s mane fruiting bodies, and wild-harvested chaga per serving
    - Fresh-brewed coffee is light, smooth, and delicious - without a single hint of mushrooms
- name: Grush Smart Electric Toothbrush Makes Brushing Fun for Kids with Interactive Brushing Games and Precise Tracking and Monitoring for Parents
  url: https://www.amazon.com/dp/B0171XH6I2/
  image: https://images-na.ssl-images-amazon.com/images/I/511JzgS3J7L.jpg
  price: $59.00
  features:
    - Reliable, easy to use hi-tech intelligent toothbrush features precise tooth tracking
    - Interactive mobile games guide brushing in real-time using patented "tooth-to-tooth navigation" tech
    - Advanced tracking and scoring system allows parental monitoring and rewards
    - World's smartest toothbrush endorsed by top pediatric dentists and award winning
- name: PDX Pet Design Licki Your Cat Brush
  url: https://www.amazon.com/dp/B01M0UXYHE/
  image: https://images-na.ssl-images-amazon.com/images/I/81kcmf5afWL._SL1500_.jpg
  price: $24.99
  features:
    - 'Soothe yourself: "licking" your cat is an oddly meditative practice, soothing for you and kitty'
    - 'Bond with your fur baby: Bond with your cat by communicating in their love language'
    - Made of a food-grade silicone designed to feel pleasurable to kitty's sensitive skin
- name: Giant Gummy Bears Party Python, 8 ft, 26.9 lbs
  url: https://www.amazon.com/dp/B00LT3L7AO/
  image: https://images-na.ssl-images-amazon.com/images/I/81gSI7G2CPL._SL1500_.jpg
  price: $149.65
  features:
    - 26 Pounds of Gummy Goodness
    - Almost 8 Feet Long
    - Over 450 Servings
    - Gluten-Free
- name: Agility Bathroom Wall Hanger Hat Bag Key Adhesive Wood Hook Vintage Spiderman Body’s Photo
  url: https://www.amazon.com/dp/B015LVB3QM/
  image: https://images-na.ssl-images-amazon.com/images/I/61EsznDuTVL._SL1000_.jpg
  price: $48.99
  features:
    - Spiderman Body's Photo
    - Material is Wood
    - The Gift for Collectible & home decor
- name: Amurleopard Unisex Barbarian Knit Beanie Octopus
  url: https://www.amazon.com/dp/B01N8ZMALA/
  image: https://images-na.ssl-images-amazon.com/images/I/61IKDovQ2fL._SL1277_.jpg
  price: $36.99
  features:
    - Currently unavailable
- name: Tanya Pet Supplies -Dog Costumes blonde Color Pet Dog Wigs-gift
  url: https://www.amazon.com/dp/B00JR5CGJ2/
  image: https://images-na.ssl-images-amazon.com/images/I/61FqulnwLqL._SL1001_.jpg
  price: $1.99
  features:
    - 'Material: Synthetic'
    - 'Color: blonde'
    - 'Size: small'
    - 'Texture: curly'
